/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dpulab.hideaway.view;

import java.awt.Color;
import org.dpulab.hideaway.utils.FileIO;
import org.dpulab.hideaway.utils.Settings;

/**
 *
 * @author dipu
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // load defaults
        String lastDirectory = Settings.getDefault().get(Settings.WORK_DIR);
        this.selectedFolderInput.setText(lastDirectory);
        
        //TODO: for test
        /*SwingUtilities.invokeLater(() -> {
            this.passwordInput.setText("TestPassword123");
            this.initializeApp();
        });*/
    }
    
    private void selectWorkFolder() {
        String folder = FileIO.getDefault().chooseFolder(this);
        this.selectedFolderInput.setText(folder);
    }
    
    private void initializeApp() {
        String workFolder = this.selectedFolderInput.getText();
        String password = new String(this.passwordInput.getPassword());
        boolean errors = false;
        
        if (workFolder == null || workFolder.isEmpty()) {
            this.selectFolderHintLabel.setText("Error: You should select a folder");
            this.selectFolderHintLabel.setForeground(Color.red);
            errors = true;
        } else {
            this.selectFolderHintLabel.setText("");
        }
        
        if (password.length() < 8) {
            this.passwordInputHintLabel.setText("Error: Password should be at least 8 characters long");
            this.passwordInputHintLabel.setForeground(Color.red);
            errors = true;
        } else {
            this.passwordInputHintLabel.setText("");
        }
        
        if (!errors) {
            Settings.getDefault().set(Settings.WORK_DIR, workFolder);
            Settings.getDefault().setSession(Settings.PASSWORD, password);
            this.dispose();
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameActionPanel = new javax.swing.JPanel();
        enterButton = new javax.swing.JButton();
        frameBodyPanel = new javax.swing.JPanel();
        selectFolderInputLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        selectedFolderInput = new javax.swing.JTextField();
        selectFolderHintLabel = new javax.swing.JLabel();
        passwordInputLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        passwordInputHintLabel = new javax.swing.JLabel();
        frameHeaderPanel = new javax.swing.JPanel();
        frameTitleLabel = new javax.swing.JLabel();
        frameSubtitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hideaway - Launcher");
        setMinimumSize(new java.awt.Dimension(550, 366));
        setModal(true);
        setName("loginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 370));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        frameActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        enterButton.setFont(enterButton.getFont().deriveFont(enterButton.getFont().getStyle() | java.awt.Font.BOLD, enterButton.getFont().getSize()+2));
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameActionPanelLayout = new javax.swing.GroupLayout(frameActionPanel);
        frameActionPanel.setLayout(frameActionPanelLayout);
        frameActionPanelLayout.setHorizontalGroup(
            frameActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        frameActionPanelLayout.setVerticalGroup(
            frameActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameActionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        selectFolderInputLabel.setFont(selectFolderInputLabel.getFont().deriveFont(selectFolderInputLabel.getFont().getSize()+2f));
        selectFolderInputLabel.setText("Select a directory to store encrypted files:");

        browseButton.setFont(browseButton.getFont().deriveFont(browseButton.getFont().getSize()+1f));
        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        selectedFolderInput.setEditable(false);
        selectedFolderInput.setFont(selectedFolderInput.getFont());
        selectedFolderInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectedFolderInputMouseClicked(evt);
            }
        });

        selectFolderHintLabel.setForeground(new java.awt.Color(0, 153, 153));
        selectFolderHintLabel.setText("The folder to store encrypted files. You can select a completely new folder.");

        passwordInputLabel.setFont(passwordInputLabel.getFont().deriveFont(passwordInputLabel.getFont().getSize()+2f));
        passwordInputLabel.setText("Enter your password here:");

        passwordInput.setFont(passwordInput.getFont());
        passwordInput.setToolTipText("Enter your password");
        passwordInput.setEchoChar('\u25cf');
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });

        passwordInputHintLabel.setForeground(new java.awt.Color(0, 153, 153));
        passwordInputHintLabel.setText("Do not loose it. Otherwise, access to your files will be lost permanently.");

        javax.swing.GroupLayout frameBodyPanelLayout = new javax.swing.GroupLayout(frameBodyPanel);
        frameBodyPanel.setLayout(frameBodyPanelLayout);
        frameBodyPanelLayout.setHorizontalGroup(
            frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameBodyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectFolderHintLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordInput)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frameBodyPanelLayout.createSequentialGroup()
                        .addComponent(selectedFolderInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordInputHintLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectFolderInputLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        frameBodyPanelLayout.setVerticalGroup(
            frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBodyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(selectFolderInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedFolderInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(selectFolderHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(passwordInputHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        frameHeaderPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 204, 204)));

        frameTitleLabel.setFont(frameTitleLabel.getFont().deriveFont(frameTitleLabel.getFont().getSize()+24f));
        frameTitleLabel.setForeground(new java.awt.Color(153, 102, 0));
        frameTitleLabel.setText("Hideaway");
        frameTitleLabel.setToolTipText("");
        frameTitleLabel.setDoubleBuffered(true);

        frameSubtitleLabel.setFont(frameSubtitleLabel.getFont().deriveFont(frameSubtitleLabel.getFont().getSize()+6f));
        frameSubtitleLabel.setForeground(new java.awt.Color(0, 153, 153));
        frameSubtitleLabel.setText("<Secure yourself with confidence>");

        javax.swing.GroupLayout frameHeaderPanelLayout = new javax.swing.GroupLayout(frameHeaderPanel);
        frameHeaderPanel.setLayout(frameHeaderPanelLayout);
        frameHeaderPanelLayout.setHorizontalGroup(
            frameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameHeaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(frameTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameSubtitleLabel)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        frameHeaderPanelLayout.setVerticalGroup(
            frameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameHeaderPanelLayout.createSequentialGroup()
                .addGroup(frameHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameHeaderPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(frameTitleLabel))
                    .addGroup(frameHeaderPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(frameSubtitleLabel)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frameHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frameBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frameHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(frameBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(frameActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        this.initializeApp();
    }//GEN-LAST:event_enterButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        this.selectWorkFolder();
    }//GEN-LAST:event_browseButtonActionPerformed

    private void selectedFolderInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectedFolderInputMouseClicked
        this.selectWorkFolder();
    }//GEN-LAST:event_selectedFolderInputMouseClicked

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        this.initializeApp();
    }//GEN-LAST:event_passwordInputActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Settings.getDefault().setSession("PASSWORD", null);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JPanel frameActionPanel;
    private javax.swing.JPanel frameBodyPanel;
    private javax.swing.JPanel frameHeaderPanel;
    private javax.swing.JLabel frameSubtitleLabel;
    private javax.swing.JLabel frameTitleLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordInputHintLabel;
    private javax.swing.JLabel passwordInputLabel;
    private javax.swing.JLabel selectFolderHintLabel;
    private javax.swing.JLabel selectFolderInputLabel;
    private javax.swing.JTextField selectedFolderInput;
    // End of variables declaration//GEN-END:variables
}
