/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dpulab.hideaway.view;

/**
 *
 * @author dipu
 */
public class RenameDialog extends javax.swing.JDialog {

    public enum DialogResult {
        SKIP,
        REPLACE,
        RENAME,
        UNKNOWN
    }

    /**
     * Make a new instance of the RenameDialog.
     * @param parent
     * @param message
     * @param initialValue
     * @param rememberBox
     * @return 
     */
    public static RenameDialog makeDialog(
            java.awt.Frame parent, String message, String initialValue, boolean rememberBox) {
        RenameDialog dialog = new RenameDialog(parent);
        dialog.setMessage(message);
        dialog.setInitialInput(initialValue);
        dialog.setRememberVisibility(rememberBox);
        return dialog;
    }

    private DialogResult result = DialogResult.UNKNOWN;

    /**
     * Creates new form RenameDialog
     *
     * @param parent
     */
    public RenameDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    private void setAction(DialogResult result) {
        this.result = result;
        this.setVisible(false);
        this.dispose();
    }

    /**
     * @return the result
     */
    public DialogResult getDialogResult() {
        return this.result;
    }

    /**
     * @return the entered input
     */
    public String getInputText() {
        return this.inputText.getText();
    }

    /**
     * @return whether to remember
     */
    public boolean isRemember() {
        return this.rememberCheckbox.isSelected();
    }

    /**
     * @param result the result to set
     */
    public void setDialogResult(DialogResult result) {
        this.result = result;
    }

    /**
     * @param text the text to set
     */
    public void setMessage(String text) {
        this.messageText.setText(text);
    }

    /**
     * @param text the text to set
     */
    public void setInputInput(String text) {
        this.inputHint.setText(text);
    }

    /**
     * @param text the text to set
     */
    public void setInitialInput(String text) {
        this.inputText.setText(text);
    }

    /**
     * @param text the text to set
     */
    public void setInputLabel(String text) {
        this.inputTextLabel.setText(text);
    }

    /**
     * @param value True to mark the remember box as checked
     */
    public void setRemember(boolean value) {
        this.rememberCheckbox.setSelected(value);
    }

    /**
     * @param visible True to show the remember check box
     */
    public void setRememberVisibility(boolean visible) {
        this.rememberCheckbox.setVisible(visible);
    }

    /**
     * @param text the text to set
     */
    public void setSkipButton(String text) {
        this.skipButton.setText(text);
    }

    /**
     * @param text the text to set
     */
    public void setReplaceButton(String text) {
        this.replaceButton.setText(text);
    }

    /**
     * @param text the text to set
     */
    public void setRenameButton(String text) {
        this.renameButton.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameBodyPanel = new javax.swing.JPanel();
        inputTextLabel = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        inputHint = new javax.swing.JLabel();
        messageText = new javax.swing.JLabel();
        frameActionPanel = new javax.swing.JPanel();
        renameButton = new javax.swing.JButton();
        skipButton = new javax.swing.JButton();
        replaceButton = new javax.swing.JButton();
        rememberCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose action");
        setMinimumSize(new java.awt.Dimension(570, 210));
        setPreferredSize(new java.awt.Dimension(570, 230));

        inputTextLabel.setFont(inputTextLabel.getFont().deriveFont(inputTextLabel.getFont().getSize()+2f));
        inputTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inputTextLabel.setText("New name:");

        inputText.setFont(inputText.getFont());

        inputHint.setForeground(new java.awt.Color(0, 153, 153));
        inputHint.setText("Choose a different name than this one");

        messageText.setText("<html>Another file with similar name exists in current folder. <br>\nEither pick a new name, replace old file or skip copying this file.</html>");

        javax.swing.GroupLayout frameBodyPanelLayout = new javax.swing.GroupLayout(frameBodyPanel);
        frameBodyPanel.setLayout(frameBodyPanelLayout);
        frameBodyPanelLayout.setHorizontalGroup(
            frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBodyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageText)
                    .addGroup(frameBodyPanelLayout.createSequentialGroup()
                        .addComponent(inputTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputText))))
                .addGap(25, 25, 25))
        );
        frameBodyPanelLayout.setVerticalGroup(
            frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameBodyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(frameBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextLabel)
                    .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(inputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        frameActionPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 102, 102)));

        renameButton.setFont(renameButton.getFont().deriveFont(renameButton.getFont().getStyle() | java.awt.Font.BOLD, renameButton.getFont().getSize()+2));
        renameButton.setText("Rename");
        renameButton.setToolTipText("Save the current file with a different name");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        skipButton.setFont(skipButton.getFont().deriveFont(skipButton.getFont().getSize()+2f));
        skipButton.setText("Skip");
        skipButton.setToolTipText("Do not copy the current file");
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });

        replaceButton.setFont(replaceButton.getFont().deriveFont(replaceButton.getFont().getSize()+2f));
        replaceButton.setText("Replace");
        replaceButton.setToolTipText("Replace the old one with this file");
        replaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceButtonActionPerformed(evt);
            }
        });

        rememberCheckbox.setText("Remember this action");

        javax.swing.GroupLayout frameActionPanelLayout = new javax.swing.GroupLayout(frameActionPanel);
        frameActionPanel.setLayout(frameActionPanelLayout);
        frameActionPanelLayout.setHorizontalGroup(
            frameActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameActionPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rememberCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        frameActionPanelLayout.setVerticalGroup(
            frameActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rememberCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameActionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frameBodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(frameBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(frameActionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        this.setAction(DialogResult.RENAME);
    }//GEN-LAST:event_renameButtonActionPerformed

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        this.setAction(DialogResult.SKIP);
    }//GEN-LAST:event_skipButtonActionPerformed

    private void replaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceButtonActionPerformed
        this.setAction(DialogResult.REPLACE);
    }//GEN-LAST:event_replaceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frameActionPanel;
    private javax.swing.JPanel frameBodyPanel;
    private javax.swing.JLabel inputHint;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel inputTextLabel;
    private javax.swing.JLabel messageText;
    private javax.swing.JCheckBox rememberCheckbox;
    private javax.swing.JButton renameButton;
    private javax.swing.JButton replaceButton;
    private javax.swing.JButton skipButton;
    // End of variables declaration//GEN-END:variables

}
